[package]
name = "version-rs"
version = "0.1.0"
authors = ["Steven Stanfield <steve@eucleo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.7"
